# site settings

title: Rachel
description: Rachel's Resume
taglong: Jekyll theme for a beautiful online CV
tagshort: Jekyll theme
url: https://gsantella.github.io/cvless/
baseurl: "cvless"
permalink: pretty
repo: https://github.com/gsantella/cvless

# author settings

author:
  name: Rachel
  email: millsrachel3730@gmail.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  facebook: adam.lacue
  github: username
  instagram: 
  linkedin: username
  stackoverflow: 0000000/username
  twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
